const { images } = require("../constants");

const dummyData = [
  {
    id: "1",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "6",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "5",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "7",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "8",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "2",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "3",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "4",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "9",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "10",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "60",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "50",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "70",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "80",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "20",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "30",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "40",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "90",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "11",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "61",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "51",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "71",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "81",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "21",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "31",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "41",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "91",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "12",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "62",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "52",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "72",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "82",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "22",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "32",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "42",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "92",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "13",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "63",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "53",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "73",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "83",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "23",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "33",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "43",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "93",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "14",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "64",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "54",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "74",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "84",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "24",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "34",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "44",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "94",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "15",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "65",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "55",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "75",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "85",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "25",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "35",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "45",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "95",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "16",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "66",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "56",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "76",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "86",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "26",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "36",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "46",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "96",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "17",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "67",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "57",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "77",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "87",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "27",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "37",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "47",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "97",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
  {
    id: "18",
    name: "Tabitha Potter",
    user_name: "mis_potter",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post,
    timestamp: "14h",
  },
  {
    id: "68",
    name: "Tori Pots",
    user_name: "tori_lexa_24",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post6,
    timestamp: "14h",
  },
  {
    id: "58",
    name: "Sunny",
    user_name: "sunny_69",
    avatar: images.profile2,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post5,
    timestamp: "14h",
  },
  {
    id: "78",
    name: "Mahi",
    user_name: "mahi_kapoor",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post7,
    timestamp: "14h",
  },
  {
    id: "88",
    name: "Jane",
    user_name: "Jane_re2",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post8,
    timestamp: "14h",
  },
  {
    id: "28",
    name: "Kareenaa",
    user_name: "kareenaa",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post2,
    timestamp: "14h",
  },
  {
    id: "38",
    name: "Salena",
    user_name: "salena",
    avatar: images.profile3,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post3,
    timestamp: "14h",
  },
  {
    id: "48",
    name: "Alexa",
    user_name: "alexa_32",
    avatar: images.profile4,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post4,
    timestamp: "14h",
  },
  {
    id: "98",
    name: "Jacqulene",
    user_name: "Jacqulene_3434",
    avatar: images.profile,
    description: `Kobe’s passing is really sticking with me in a way I didn’t expect.\n\nHe was an icon, the kind of person who wouldn’t die this way. My wife compared it to Princess Di’s accident.`,
    post: images.post9,
    timestamp: "14h",
  },
];

module.exports = { dummyData };
